name: rest_graphql
description: App que integra GraphQL (Rick and Morty) y REST (JSONPlaceholder)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Para REST API
  http: ^1.1.0
  
  # Para GraphQL
  graphql_flutter: ^5.1.2
  
  # Para manejo de estado
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true